### PR TITLE
Save & Load distraction state

### PR DESCRIPTION
**Pull request by takuma-yoneda**
The only last 5 commits are relevant to the title.
Other commits should have been included in other PRs (including #1 and #2).

Summary (of the last 5 commits):
- remove dependency on gym-dmc
- set distraction_types to change the type of distractions
- set distracting_seed
- save & load distraction state

You can try save & load functionality with `specs/gym_dc_test.py` script.
This should generate `reprod_figures/save_and_load/ball_in_cup-catch-(easy|medium|hard)/*.png`.
You can see that the distractions in the same directory are identical.

Also in `reprod_figures/fix_distraction/ball_in_cup-catch-(easy|medium|hard)/*.png`,
you can see that the distractions are identical across episodes.

### CODE REVIEW

**Comment by takuma-yoneda** [comment]
@geyang Theses commits: c402a36 and 7245940 above are the only ones that are not included in any other PRs.
These 2 line changes apply simply discount during frame_skip. Please let me know if I should revert these on this PR.

**Comment by geyang** [comment]
Thanks @takuma-ynd ! I have pinged @ztzhang and @anuragajay

**Comment by takuma-yoneda** [comment]
@geyang Actually it seems to be reverted by myself. 
I'm sorry for the confusion. Please disregard the whole my comments on discount.

**Comment by takuma-yoneda** [comment]
I reopened it in #4 after squishing & rebasing the commits.

**Pull request closed without merging**
